### PR TITLE
Make page titles more consistent

### PR DESCRIPTION
**Pull request by rkdarst**
- I think this is a good system but we could do something else
  instead.

### CODE REVIEW

**Comment by bast** [comment]
We could use `{{ page.title }} - {{ site.title }}` and set the latter accordingly.

**Comment by rkdarst** [comment]
Good idea. I guess there could also be an override like, right?:
`{% if page.title_full %}{{page.title_full}}{% else %}{{page.title}} - {{site.title}}{% endif %}`

I originally thought `{{ page.title_full | default: page.title + "-" + site.title }}`, but I assume that's not correct syntax (and couldn't find the correct syntax), right?

**Comment by rkdarst** [comment]
Done.  I hope it's OK to not have `page.title` in index.md.

**Comment by rkdarst** [comment]
Updated based on the template-based approach.  Untested here...

**Pull request merged**
