### PR TITLE
Add page on the Reimagining Research Computing workshop

### PR DESCRIPTION
**Pull request by rkdarst**
- Placeholder page - text not finished.
- This exists for comments and contributions from others, feel free to
  push straight to this branch.

### CODE REVIEW

**Comment by rkdarst** [comment]
I added all of the notes from the workshop sticky notes.  This is ready for review.  I'd recommend a good look at the intro and try to make it more targeted to our goals.

**Comment by bast** [comment]
Thank you for writing this up! Do you prefer changes here or as a follow-up PR from me?

**Comment by rkdarst** [comment]
> Thank you for writing this up! Do you prefer changes here or as a follow-up PR from me?

Either one, doesn't matter so much to me.  I won't rebase at least and
can always make a new PR.


-- 
| Richard Darst   -   http://rkd.zgib.net/   -   pgp 0xBD356740
| "Ye shall know the truth and -- the truth shall make you free"

**Comment by bast** [comment]
Merging. It's a really good write-up and minor edits I can submit as PRs.

**Pull request merged**
