### PR TITLE
Dinner reservation, note remote attendance, clarify resources

### PR DESCRIPTION
**Pull request by rkdarst**

### CODE REVIEW

**Review by wikfeldt — APPROVED** [review]
looks good

**Comment by wikfeldt** [comment]
but one question, now there's both a hackpad and a drive doc. should both tools be used?

**Comment by rkdarst** [comment]
On Tue, Nov 12, 2019 at 07:17:10AM -0800, Kjartan Thor Wikfeldt wrote:
> but one question, now there's both a hackpad and a drive doc. should both tools be used?

Oh, you're right... I removed it from some places but not from all.

**Comment by rkdarst** [comment]
On Tue, Nov 12, 2019 at 07:17:10AM -0800, Kjartan Thor Wikfeldt wrote:
> but one question, now there's both a hackpad and a drive doc. should both tools be used?

Removed the doc from the drive, the drive is still used though for
other files/presentations/etc.  Are there more inconsistencies?

**Pull request merged**
